[build]
  command = "npm run build" # Or "yarn build" if you're using yarn
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.14.0"
  NPM_VERSION = "10.7.0"

[context.production.environment]
  NODE_VERSION = "20.14.0" # Ensure Node.js version matches your local environment
  NPM_VERSION = "10.7.0"
